---
# auto load vault vars
#- name: load vault vars
#  hosts: all
#  tasks:
#    - include_vars: group_vars/all_vault.yml

- name: python3 as default
  hosts: all
  tags:
    - python3
    - python-is-python3
    - python3-is-python
    - python-default
    - python3-default
  roles:
    - python3-default

- name: Update packages and users on all nodes
  hosts: freifunk
  tags: 
  - motd
  roles:
    - motd
    - install-bat
  tasks:
    - name: Prevent batman package auto upgrade
      dpkg_selections:
        name: bat
        selection: hold

# Note: We don't do this for hosts in external datacenters
# since we may have other hosts in the future, let's keep this for now, but commented out
#- name: Configure basic network setup for gw
#  hosts:
#     - gw01.ffbsee.net
#     - gw02.ffbsee.net
#     - map.ffbsee.net
#  tags:
#  - network
#  - interfaces
#  roles:
#    - network

- name: fail2ban
  hosts: all
  tags:
    - fail2ban
  roles:
    - name: fail2ban

- name: Configure freifunk network setup for gw
  hosts: freifunk
  tags:
  - backbone
  - fastd
  - freifunk-backbone
  - freifunk-update-script
  - fastd-install
  - fastd-config
  - wireguard
  - vxlanbackbone
  roles:
    - freifunk-backbone
    - freifunk-update-script
    - fastd-install
    - fastd-config
    - wireguard
    - vxlanbackbone

- name: Configure network routing for gw
  hosts: freifunk
  tags: 
  - routing
  - iptables
  - ip6tables
  - firewall
  roles:
   - firewall

- name: Configure network routing for gw
  hosts:
    - gw01.ffbsee.net
    - gw02.ffbsee.net
  tags: 
  - routing
  - dhcp
  - dhcpd
  - isc-dhcp
  - isc
  - isc-dhcp-server
  roles:
   - dhcpd

- name: Configure network routing for map
  hosts:
    - map.ffbsee.net
  tags: 
  - routing
  - dhcp
  - dhcpd
  - isc-dhcp
  - isc
  roles:

# Note: this is only done on gws
- name: Configure network routing for gw
  hosts:
    - gw01.ffbsee.net
    - gw02.ffbsee.net
  tags: 
  - dns
  - unbound
  - role-unbound
  - bind
  
  collections:
   - community.general
   - ansible.utils
  roles:
   - unbound
   - unbound_freifunk_tlds
   - bird

# Note: this should only be executed on one gateway
- name: Configure Intercity VPN
  hosts:
    - gw02.ffbsee.net
  tags:
  - icvpn 
  - tinc
  
  roles:
   - role: freifunk-icvpn
     when: run_icvpn == 'true'
   - role: tinc
     when: run_icvpn == 'true'

# Note: this is only done on the map server
- name: Configure web setup for gw
  hosts: map.ffbsee.net
  tags: web
  roles:
    - nginx
    - gateway-page
#    - freifunk-karte-json
#    - FFNodeList

- name: install telegraf
  hosts: all
  become: yes
  tags:
    - telegraf
  roles:
    - telegraf


- name: install re4jh/robin-exporter
  hosts: map.ffbsee.net
  tags:
    - robin
  roles:
    - ffbsee-robin-exporter
